sudo apt-get install libx11-dev \
libxi-dev \
libxrandr-dev \
libx11-xcb-dev \
libxkbcommon-x11-dev \
libxtst-dev \
libfontconfig1-dev \
libfreetype6-dev \
libxext-dev \
libxfixes-dev \
libxrender-dev \
libxcb1-dev \
libxcb-glx0-dev \
libxcb-keysyms1-dev \
libxcb-image0-dev \
libxcb-shm0-dev \
libxcb-icccm4-dev \
libxcb-sync0-dev \
libxcb-xfixes0-dev \
libxcb-shape0-dev \
libxcb-randr0-dev \
libxcb-render-util0-dev  \
libxkbcommon-dev \
libxcb-xinerama0-dev -y